# The version of the docker-compose.
version: "3.3"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  frontend:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    # image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Giving the container a name.
    # container_name: frontendapp_c
    # Mapping the port 4000 on the host machine to the port 4000 on the container.
    ports:
      - 4000:4000
    # Mapping the client directory on the host machine to the /app directory on the container.
    volumes:
      - ./frontend:/app
      - ./frontend/public:/app/public
      # - ./app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    restart: always
    tty: true
    depends_on:
      - backend

  backend:
    restart: always
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    # image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: backendapp_c
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
