version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - scs-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - scs-network

  scs-mysql-db:
    image: mysql:8.0.26
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    networks:
      - scs-network
    volumes:
      - scs-mysql-data:/var/lib/mysql

volumes:
  scs-mysql-data:
    driver: local

networks:
  scs-network:
    driver: bridge